package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/15529214579/polymarket-go/internal/journal"
	"github.com/15529214579/polymarket-go/internal/paperreport"
)

func main() {
	journalDir := flag.String("journal", "db/smartmoney-paper/journal", "paper journal directory")
	whaleLog := flag.String("whale_log", "db/smartmoney-paper/journal/whale_trades.jsonl", "whale event log used to resolve legacy labels")
	jsonOut := flag.String("json_out", "db/smartmoney-paper/wallet-performance.json", "wallet policy JSON output")
	reportOut := flag.String("report", "reports/smartmoney-paper-wallets.md", "wallet policy Markdown output")
	promotedOut := flag.String("promoted", "db/smartmoney-paper/wallets.paper-promoted.txt", "promoted wallet overlay")
	demotedOut := flag.String("demoted", "db/smartmoney-paper/wallets.paper-demoted.txt", "demoted wallet block list")
	minPositions := flag.Int("min_positions", 10, "minimum closed positions before a decision")
	promoteMinNet := flag.Float64("promote_min_net", 5, "minimum net PnL in U for promotion")
	promoteMinROI := flag.Float64("promote_min_roi", 2, "minimum net ROI percentage for promotion")
	demoteMaxNet := flag.Float64("demote_max_net", -5, "maximum net PnL in U before demotion")
	flag.Parse()

	trades, err := journal.ReadAll(*journalDir)
	if err != nil {
		fatalf("read journal: %v", err)
	}
	aliases, err := readAliases(*whaleLog)
	if err != nil {
		fatalf("read whale aliases: %v", err)
	}
	report := paperreport.AnalyzeWalletPolicy(trades, aliases, paperreport.WalletPolicyConfig{
		MinPositions:  *minPositions,
		PromoteMinNet: *promoteMinNet,
		PromoteMinROI: *promoteMinROI,
		DemoteMaxNet:  *demoteMaxNet,
	})

	body, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		fatalf("marshal report: %v", err)
	}
	if err := atomicWrite(*jsonOut, append(body, '\n')); err != nil {
		fatalf("write JSON: %v", err)
	}
	markdown := formatMarkdown(report)
	if err := atomicWrite(*reportOut, []byte(markdown)); err != nil {
		fatalf("write report: %v", err)
	}
	if err := atomicWrite(*promotedOut, []byte(formatWalletList(report, "promote"))); err != nil {
		fatalf("write promoted wallets: %v", err)
	}
	if err := atomicWrite(*demotedOut, []byte(formatWalletList(report, "demote"))); err != nil {
		fatalf("write demoted wallets: %v", err)
	}
	fmt.Printf("smartmoney-wallet-policy promoted=%d demoted=%d unresolved=%d report=%s\n", report.Promoted, report.Demoted, report.Unresolved, *reportOut)
}

func readAliases(path string) (map[string]string, error) {
	aliases := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return aliases, nil
		}
		return nil, err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	buf := make([]byte, 64*1024)
	sc.Buffer(buf, 1024*1024)
	for sc.Scan() {
		var event struct {
			Wallet string `json:"wallet"`
			Label  string `json:"label"`
		}
		if json.Unmarshal(sc.Bytes(), &event) != nil {
			continue
		}
		wallet := strings.ToLower(strings.TrimSpace(event.Wallet))
		label := strings.ToLower(strings.TrimSpace(event.Label))
		if len(wallet) != 42 || !strings.HasPrefix(wallet, "0x") || label == "" {
			continue
		}
		aliases[label] = wallet
		aliases["copytrade_"+label] = wallet
		aliases["copytrade_football_score_"+label] = wallet
	}
	return aliases, sc.Err()
}

func formatMarkdown(report paperreport.WalletPolicyReport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Smartmoney Paper Wallet Policy\n\nGenerated: %s\n\n", report.GeneratedAt.Format("2006-01-02T15:04:05Z07:00"))
	fmt.Fprintf(&b, "- Rule: at least %d closed positions; promote at net >= %+.2fU and ROI >= %+.2f%%; demote at net <= %+.2fU\n", report.Config.MinPositions, report.Config.PromoteMinNet, report.Config.PromoteMinROI, report.Config.DemoteMaxNet)
	fmt.Fprintf(&b, "- Decisions: %d promoted / %d demoted / %d unresolved\n\n", report.Promoted, report.Demoted, report.Unresolved)
	b.WriteString("| Decision | Wallet | Positions | Capital | Fees | Net | ROI | W/L/F | Reason |\n")
	b.WriteString("|---|---|---:|---:|---:|---:|---:|---:|---|\n")
	for _, row := range report.Wallets {
		wallet := row.Wallet
		if wallet == "" {
			wallet = row.Source
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %.2f | %.2f | %+.2f | %+.2f%% | %d/%d/%d | %s |\n",
			row.Decision, wallet, row.Positions, row.CapitalUSD, row.FeesUSD, row.NetPnL, row.ROI, row.Wins, row.Losses, row.Flat, row.Reason)
	}
	return b.String()
}

func formatWalletList(report paperreport.WalletPolicyReport, decision string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by smartmoney-wallet-policy; decision=%s\n", decision)
	for _, row := range report.Wallets {
		if row.Decision != decision || row.Wallet == "" {
			continue
		}
		list := "paper_" + decision + "d"
		tier := ""
		if decision == "promote" {
			tier = " tier=B"
		}
		fmt.Fprintf(&b, "%s # list=%s%s localPaperPositions=%d localPaperROI=%.2f%% localPaperPnL=%+.2fU\n",
			row.Wallet, list, tier, row.Positions, row.ROI, row.NetPnL)
	}
	return b.String()
}

func atomicWrite(path string, body []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	f, err := os.CreateTemp(dir, ".wallet-policy-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer os.Remove(tmp)
	if _, err := f.Write(body); err != nil {
		f.Close()
		return err
	}
	if err := f.Chmod(0o644); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
